development:
  adapter: postgresql
  database: wildlife_tracker_development

test:
  adapter: postgresql
  database: wildlife_tracker_test

# production:
#   adapter: postgresql
#   database: wildlife_tracker_production
